# Generated by Django 4.0.2 on 2022-04-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelapp', '0003_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
